development: 
  adapter: postgresql
  encoding: unicode
  database: phase_two_project-development
  pool: 2
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: phase_two_project-production